AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template to create a bucket that stores zip files of the code used by lambda functions

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: code-coffee-shop-bkt
      
Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Export: 
      Name: BucketName

  BucketArn:
    Value: !GetAtt S3Bucket.Arn
    Export:
      # The name must be unique within the AWS account and region
      Name: S3BucketArn
  